routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

// Login and register
Auth::routes();

// Homepage Landing
Route::get('/', 'IndexController@index')->name('home');

//Features
Route::get('/features', 'FeaturesController@index');

// About Us
Route::get('/about', 'AboutUsController@index');
Route::group(
    ['middleware' => 'auth'],
    function () {
        Route::resource('/admin/about', 'AboutUsController');
    }
);

// Contact Us
Route::get('/contact', 'ContactController@contactUS');
Route::post('/contact', ['as' => 'contactus.store', 'uses' => 'ContactController@contactSaveData']);

Route::group(
    ['middleware' => 'auth'],
    function () {
        Route::get('/admin/contact', 'ContactController@index');
    }
);

// Blog
Route::group(['prefix' => 'blog'], function () {
    Route::resource('/post', 'BlogsController', ['only' => ['index', 'show']]);
    Route::post('/post/{title}/comment', 'BlogsController@comment')->middleware('auth');
});

// Admin Dashboard
Route::get('/admin/home', 'HomeController@index')->name('home');

// Admin Page
Route::group(
    ['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'],
    function () {
        // User Management
        Route::resource('user', 'UserController', ['except' => ['show']]);
        Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfilesController@edit']);
        Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfilesController@update']);
        Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfilesController@password']);
        // Admin Blogs
        Route::resource('/blog/posts', 'PostController');
        Route::put('/blog/posts/{post}/publish', 'PostController@publish')->middleware('admin');
        Route::resource('/blog/categories', 'CategoryController', ['except' => ['show']]);
        Route::resource('/blog/tags', 'TagController', ['except' => ['show']]);
        Route::resource('/blog/comments', 'CommentController', ['only' => ['index', 'destroy']]);
    }
);

// Summary
Route::get('/summary', 'SummaryController@index');
// Table
Route::get('/table', 'TableController@index');
// Maps
Route::get('/maps', 'MapsController@index');

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\About;
use App\ContactUS;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    public function index()
    {
        $contacts = ContactUS::latest()->paginate(10);
        return view('admin.contacts.index', compact('contacts'));
    }
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function contactUS()
    {
        // $about = $about->load(['about']);
        // return view('contact', compact('post'));
        $about = ContactUS::getAboutData();

        // Pass to view
        return view('contact')->with("about", $about);
        // return view('contact');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function contactSaveData(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email',
            'subject' => 'required',
            'message' => 'required'
        ]);

        ContactUS::create($request->all());

        return back()->with('success', 'Thanks for contacting us!');
        // return redirect()->route('contact')->with('success', 'Post deleted successfully!');
    }
}

resources/views/admin/contacts/index.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="container mb-5 mt-5">
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif
    <table class="table table-bordered">
        <tr>
            {{-- <th width="80px">No</th> --}}
            <th>Name</th>
            <th>Email</th>
            <th>Subject </th>
            <th>Message </th>
        </tr>
        @foreach ($contacts as $contact)
        <tr>
            {{-- <td>1</td>
            <td>{{ $about->name }}</td>
            <td>{{ $about->email }}</td>
            <td>
                <a class="btn btn-primary btn-sm" href="{{ route('about.show',$about->id) }}">Show</a>
                <a class="btn btn-info btn-sm" href="{{ route('about.edit',$about->id) }}">Edit</a>
                {!! Form::open(['method' => 'DELETE','route' => ['about.destroy', $about->id],'style'=>'display:inline']) !!}
                <button type="submit" style="display: inline;" class="btn btn-danger btn-sm">Deleted</button>
                {!! Form::close() !!}
            </td> --}}
            <td>{{ $contact->name }}</td>
            <td>{{ $contact->email }}</td>
            <td>{{ $contact->subject }}</td>
            <td>{{ $contact->message }}</td>
        </tr>
        @endforeach
    </table>
    {!! $contacts->render() !!}
</div>
@endsection