routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

// Login and register
Auth::routes();

// Homepage Landing
Route::get('/', 'IndexController@index')->name('home');

//Features
Route::get('/features', 'FeaturesController@index');

// About Us
Route::get('/about', 'AboutUsController@index');
Route::group(
    ['middleware' => 'auth'],
    function () {
        Route::resource('/admin/about', 'AboutUsController');
    }
);

// Contact Us
Route::get('/contact', 'ContactController@contactUS');
Route::post('/contact', ['as' => 'contactus.store', 'uses' => 'ContactController@contactSaveData']);

Route::group(
    ['middleware' => 'auth'],
    function () {
        Route::get('/admin/contact', 'ContactController@index');
    }
);

// Blog
Route::group(['prefix' => 'blog'], function () {
    Route::resource('/post', 'BlogsController', ['only' => ['index', 'show']]);
    Route::post('/post/{title}/comment', 'BlogsController@comment')->middleware('auth');
});

// Admin Dashboard
Route::get('/admin/home', 'HomeController@index')->name('home');

// Admin Page
Route::group(
    ['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'],
    function () {
        // User Management
        Route::resource('user', 'UserController', ['except' => ['show']]);
        Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfilesController@edit']);
        Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfilesController@update']);
        Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfilesController@password']);
        // Admin Blogs
        Route::resource('/blog/posts', 'PostController');
        Route::put('/blog/posts/{post}/publish', 'PostController@publish')->middleware('admin');
        Route::resource('/blog/categories', 'CategoryController', ['except' => ['show']]);
        Route::resource('/blog/tags', 'TagController', ['except' => ['show']]);
        Route::resource('/blog/comments', 'CommentController', ['only' => ['index', 'destroy']]);
    }
);

// Summary
Route::get('/summary', 'SummaryController@index');
// Table
Route::get('/table', 'TableController@index');
// Maps
Route::get('/maps', 'MapsController@index');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name'];

    protected static function boot()
    {
        parent::boot();
        static::deleting(function ($category) {
            $category->posts()->delete();
        });
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Category;
use App\Policies\PostPolicy;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::withCount('posts')->orderBy('created_at', 'desc')->paginate(10);
        return view('admin.categories.index', compact('categories'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', Category::class);
        $this->validate($request, ['name' => 'required']);
        Category::create(['name' => $request->name]);
        return redirect()->route('categories.index')->with('success', 'Category created successfully!');
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        if ($category->user_id != auth()->user()->id && auth()->user()->is_admin == false) {
            return redirect()->route('categories.index')->with('success', 'Sorry you are not Admin. You can not edit other peoples post.');
        }
        return view('admin.categories.edit', compact('category'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->authorize('update', $category);
        $this->validate($request, ['name' => 'required']);
        $category->update($request->all());
        return redirect()->route('categories.index')->with('success', 'Category updated successfully!');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        if (!Gate::check('forceDelete', $category)) {
            return redirect()->route('categories.index')->with('success', 'Sorry you are not admin. You can not delete any category. Just create a new category!');
        }
        $category->delete();
        return redirect()->route('categories.index')->with('success', 'Category deleted successfully!');
    }
}

resources/views/admin/categories/_form.blade.php
<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
        {!! Form::label('name', 'Name', ['class' => 'col-md-2 control-label']) !!}

        <div class="col-md-8">
            {!! Form::text('name', null, ['class' => 'form-control', 'required', 'autofocus']) !!}

            <span class="help-block">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
        </div>
    </div>

resources/views/admin/categories/create.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12 mb-5 mt-5">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1>Category
                        <a href="{{ url('admin/blog/categories/') }}" class="btn btn-info pull-right">Go Back</a>
                    </h1>
                </div>
                <div class="panel-body">
                    {!! Form::open(['url' => '/admin/blog/categories', 'class' => 'form-horizontal', 'role' => 'form']) !!}
                    @include('admin.categories._form')
                    <div class="form-group">
                        <div class="col-md-8 col-md-offset-2">
                            <button type="submit" class="btn btn-primary">
                                Create
                            </button>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>

    </div>
</div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="container">
            <div class="row">
                <div class="col-md-12 mb-5 mt-5">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h1>Edit Category
                                <a href="{{ url('admin/blog/categories/') }}" class="btn btn-danger pull-right">Cancel</a>
                            </h1>
                        </div>
                        <div class="panel-body">
                        {!! Form::model($category, ['method' => 'PUT', 'url' => "/admin/blog/categories/{$category->id}", 'class' => 'form-horizontal', 'role' => 'form']) !!}
                            @include('admin.categories._form')
                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-2">
                                    <button type="submit" class="btn btn-primary">Update</button>
                                </div>
                            </div>
                        {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12 mb-5 mt-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                    @endif
                    <div class="panel-heading">
                        <h1>Category
                            <a href="{{ url('admin/blog/categories/create') }}" class="btn btn-info pull-right">Create
                                New</a>
                        </h1>
                    </div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Post Count</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($categories as $category)
                            <tr>
                                <td>{{ $category->name }}</td>
                                <td>{{ $category->posts_count }}</td>
                                <td>
                                    <a href="{{ url("/admin/blog/categories/{$category->id}/edit") }}"
                                        class="btn btn-xs btn-info">Edit</a>
                                    <form action="{{ route('categories.destroy',$category->id) }}" method="POST"
                                        style="display: inline;">
                                        @csrf @method('DELETE')
                                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="2">No category available.</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                    {!! $categories->links() !!}
                </div>
            </div>
        </div>

    </div>
</div>
@endsection